fix: make multiple scopes work.
inspectIT/inspectit-gepard-agent pull request #16
Opened 2024-09-06 11:55 UTC by levinkerschberger

ConfigurationResolver had only access to the first scope with the same fqn (See: InstrumentationConfiguration.java). 
Thus only one scope works, if there are multiple with the same fqn.

Now all Scopes, where the fqn is included are returned to ConfigurationResolver.

Have to flatten the MethodNames of the Scope-List now before I pass them into the MethodMatcher.

Dont like ConfigurationResolver.java:94: `ElementMatchers.namedOneOf(methodNames.toArray(String[]::new));`
Is there any prettier syntax to convert that list to a stinknormal array?

2024-09-09 08:58 UTC, EddeCCC requested changes

2024-09-09 09:02 UTC, EddeCCC commented on src/main/java/rocks/inspectit/gepard/agent/resolver/ConfigurationResolver.java
> +            .filter(Objects::nonNull) // Filter out null method lists
inspectit-ocelot uses a [MatcherChainBuilder](https://github.com/inspectIT/inspectit-ocelot/blob/e2e8a4c06ab696a85feee40d2c1f82ec91d3eb07/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/matcher/MatcherChainBuilder.java#L13) to link several ElementMatchers. Maybe we could use a similar approach to add an `any()`-matchers, as soons as a `null` list was collected.

2024-09-09 09:07 UTC, levinkerschberger commented on src/main/java/rocks/inspectit/gepard/agent/internal/configuration/model/instrumentation/InstrumentationConfiguration.java
> +  public List<Scope> getAllScopeWithFqn(String fqn) {
For sure.

2024-09-09 09:12 UTC, levinkerschberger commented on src/main/java/rocks/inspectit/gepard/agent/resolver/ConfigurationResolver.java
> +    List<Scope> scopes = getConfiguration().getAllScopeWithFqn(typeDescription.getName());
Yes.

2024-09-09 09:13 UTC, levinkerschberger commented on src/main/java/rocks/inspectit/gepard/agent/resolver/ConfigurationResolver.java
> +    // Get the configuration and retrieve all matching scopes
True :)

2024-09-09 13:06 UTC, levinkerschberger commented on src/main/java/rocks/inspectit/gepard/agent/resolver/ConfigurationResolver.java
> +            .filter(Objects::nonNull) // Filter out null method lists
Refactored in changes below.

2024-09-10 09:12 UTC, EddeCCC requested changes
Can you apply spotless one more time?

2024-09-10 09:12 UTC, EddeCCC commented on src/main/java/rocks/inspectit/gepard/agent/resolver/scope/ScopeResolver.java
> +  private boolean containsWholeClassScope(List<Scope> scopes) {
I'm not happy with the wording. For the whole class scope, the constructor is still missing.
Can we name it something like `containsAllMethods()`.

2024-09-10 09:12 UTC, EddeCCC commented on src/main/java/rocks/inspectit/gepard/agent/resolver/scope/ScopeResolver.java
> +  private boolean isWholeClassScope(Scope scope) {
Could you also adapt the wording here

2024-09-10 09:12 UTC, EddeCCC commented on src/main/java/rocks/inspectit/gepard/agent/resolver/matcher/MatcherChainBuilder.java
Could you also replace the null checks if the methods from `Objects`? Since they are used within the whole agent.

2024-09-10 09:12 UTC, EddeCCC commented on src/main/java/rocks/inspectit/gepard/agent/resolver/scope/ScopeResolver.java
If you'd create a test for `ScopeResolver`, it would boost the test coverage.
It will probably be similar tests as in `ConfigurationResolverTest`, since the `ConfigurationResolver` just calls the `ScopeResolver`.

2024-09-10 12:04 UTC, levinkerschberger commented on src/test/java/rocks/inspectit/gepard/agent/resolver/matcher/CustomElementMatchersTest.java
> +        }
Sure. I will add testutils with a static assertMatcherMatches().

2024-09-10 12:04 UTC, levinkerschberger commented on src/main/java/rocks/inspectit/gepard/agent/resolver/matcher/MatcherChainBuilder.java
> +  private ElementMatcher.Junction<T> matcher = null;
Yop

2024-09-10 12:06 UTC, levinkerschberger commented on src/main/java/rocks/inspectit/gepard/agent/resolver/scope/ScopeResolver.java
> +  ConfigurationHolder holder;
private and final.

2024-09-10 12:06 UTC, levinkerschberger commented on src/main/java/rocks/inspectit/gepard/agent/resolver/scope/ScopeResolver.java
> +  public ElementMatcher.Junction<MethodDescription> buildMethodMatcher(
I don´t think that´s correct, cause it does more than a getter.

2024-09-10 12:12 UTC, levinkerschberger commented on src/main/java/rocks/inspectit/gepard/agent/resolver/matcher/MatcherChainBuilder.java
Sure

2024-09-10 12:17 UTC, EddeCCC commented on src/main/java/rocks/inspectit/gepard/agent/resolver/scope/ScopeResolver.java
> +  public ElementMatcher.Junction<MethodDescription> buildMethodMatcher(
True, shouldn't we then also rename the method in `ConfigurationResolver` to `buildMethodMatcher()`?

2024-09-10 12:19 UTC, EddeCCC commented on src/main/java/rocks/inspectit/gepard/agent/resolver/scope/ScopeResolver.java
Nvm, jacoco is smart...

2024-09-10 14:04 UTC, EddeCCC approved these changes

2024-09-10 14:08 UTC, merged