Feature/fix scope updates
inspectIT/inspectit-gepard-agent pull request #17
Opened 2024-09-12 12:54 UTC by EddeCCC

Fixed recognition of configuration updates.

2024-09-16 14:24 UTC, levinkerschberger requested changes

2024-09-16 14:24 UTC, levinkerschberger commented on src/main/java/rocks/inspectit/gepard/agent/internal/instrumentation/InstrumentationState.java
>    public boolean isInstrumented(InstrumentedType instrumentedType) {
isIncluded() might be a better name, cause state.isInstrumented() sounds like asking if the state is instrumented.

2024-09-16 14:24 UTC, levinkerschberger commented on src/main/java/rocks/inspectit/gepard/agent/internal/instrumentation/InstrumentationState.java
>    public boolean isInstrumented(InstrumentedType instrumentedType) {
or exits()

2024-09-16 14:24 UTC, levinkerschberger commented on src/main/java/rocks/inspectit/gepard/agent/transformation/DynamicTransformer.java
> +    ClassInstrumentationConfiguration currentConfig =
It would also make sense to ask for the state at this point, instead of resolving something.
state.getClassInstConfigByType(type) or something

2024-09-16 14:24 UTC, levinkerschberger commented on src/main/java/rocks/inspectit/gepard/agent/transformation/DynamicTransformer.java
>        ElementMatcher.Junction<MethodDescription> methodMatcher =
and then something like 
currentConfig().scope().getMethodMatcher() would look nice

2024-09-16 14:40 UTC, levinkerschberger reviewed
Please try to separate resolving, instrumenting and state more.

2024-09-16 14:47 UTC, EddeCCC commented on src/main/java/rocks/inspectit/gepard/agent/internal/configuration/model/instrumentation/Scope.java
> +    this.methods = methods;
I would keep it to stay closer to the inspectIT Ocelot configuration.

2024-09-17 07:27 UTC, levinkerschberger approved these changes

2024-09-17 07:29 UTC, merged